会場を株式会社インプレスに変更した
koko2718/ichiyasaGitSample pull request #1
Opened 2024-11-21 11:48 UTC by koko2718

###
名前つけた

2024-11-21 12:16 UTC, tora-kuro commented
よくできている。

2024-11-22 09:13 UTC, tora-kuro commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
株式会社インプレスと正式な名前にしていただけますか？

2024-11-22 09:14 UTC, tora-kuro commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
ねこかわゆす

2024-11-22 09:27 UTC, tora-kuro commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
インプレスってなに？

2024-11-22 09:32 UTC, koko2718 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
俺たちが務めているかいしゃだよ・・・

2024-11-22 09:45 UTC, tora-kuro commented
休憩時間ながくない？

2024-11-22 09:46 UTC, tora-kuro requested changes

2024-11-22 09:46 UTC, tora-kuro commented on index.html
>                          <p>3月23日 19:00開始</p>
あ

2024-11-22 09:48 UTC, koko2718 commented on index.html
>                          <p>3月23日 19:00開始</p>
い

2024-11-22 09:50 UTC, tora-kuro approved these changes

2024-11-22 10:09 UTC, merged